### ISSUE TITLE
funny shan char still there from line 88

### ISSUE THREAD

**Issue by bksubhuti** [dhammacakka/pm12e#10]
![image](https://user-images.githubusercontent.com/18184280/103161933-bdc23080-4817-11eb-9e90-c3cb5faf78a7.png)

**Comment by bksubhuti** [comment]
![image](https://user-images.githubusercontent.com/18184280/103162001-be0efb80-4818-11eb-9c27-e79282239819.png)
![image](https://user-images.githubusercontent.com/18184280/103162010-f282b780-4818-11eb-9b84-fa4fc5d5f1a5.png)

**Comment by wai54** [comment]
![Uploading D4C5F1D4-26ED-47B0-931A-669D07B9E3C1.jpeg…]()

**Comment by wai54** [comment]
In line 88 abbha it should be ဘ under ဗ
ဗ႓

**Comment by wai54** [comment]
In line 251 abbhudaya it should be ဘ under ဗ with
ု on the right side ဗ႓ဳ

**Comment by bksubhuti** [comment]
I will see if google sheets can convert the original better

**Comment by bksubhuti** [comment]
I loaded pm1 csv which I think is the original to google sheets which auto converts using fuzzy.. but .. looks like the shan char is there.  so we might have to remove it manually.

**Comment by bksubhuti** [comment]
line 154  the other words in reference are also problems 
![image](https://user-images.githubusercontent.com/18184280/103164050-b1000580-4834-11eb-952a-7fbb1894c281.png)
