### ISSUE TITLE
skip button

### ISSUE THREAD

**Issue by bksubhuti** [dhammacakka/pm12e#20]
Daw Wai2 requested a skip button to help make things easier for Myanmar Culture.
They want to skip and do the easy ones. 

Now that things have moved forward, we can support it.
either make a new category ask "skipped"
or make a cl=-1

Then there needs to be quick interface for daw wai2 to grab these and do the sorting.

The reason to not make these "medium" is because mediums are pulled from maZar2 who is paid.
This way, daw Wai can decide to translate, send to specialist or send to maZar2 as "medium"

**Comment by sumbodhi** [comment]
Skip is fine as the DB already supports this. Every user has a 'Skipped words' list and words from that list never get served to the user once skipped.

**Comment by bksubhuti** [comment]
good
