### ISSUE TITLE
Myanmar Language Signup

### ISSUE THREAD

**Issue by bksubhuti** [dhammacakka/pm12e#22]
If there is a switch so that Myanmar people can sign up directly in Myanmar and have the profile for that, that would be good.

I will provide a signup translation

**Comment by sumbodhi** [comment]
No switch, but the default language could be Myanmar. Or the site might detect the IP and use the IP country language when not logged in. Newly registered users have their language preference set to 'Myanmar'

**Comment by bksubhuti** [comment]
i have text.. actually everyone would know myanmar :)  
I will think more about this.. it is least of priority.  I can sign them up manually.  I don't think there will be many.
But we will keep this issue open for reference.

**Comment by bksubhuti** [comment]
i think not needed.. since they should know english
